# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false


matrix:
  include:
  - r: 3.4.0
  - r: release

  allow_failures:

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

