---
title: "538 Football Club Rankings"
author: "Michael Clark"
date: <span style="font-style:normal;font-family:'Open Sans'">`r Sys.Date()`</span>
output:
  html_vignette:
    toc: true
    toc_depth: 3
    df_print: kable
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = T, message=F, warning=F, error=F, collapse = TRUE,
                      comment=NA, R.options=list(width=220),   # code 
                      dev.args=list(bg = 'transparent'), dev='png',                                 # viz
                      fig.align='center', out.width='75%', fig.asp=.75,                 
                      cache.rebuild=F, cache=F)                                                     # cache
```





## 538 Football Club Rankings


### Installation

Use the `devtools` package to install this package from GitHub.

```{r install, eval=FALSE}
devtools::install_github('m-clark/five38clubrankings')
```


### Get the rankings and summaries

The main function gets the club rankings, while others will use dplyr to get by-country and by-league averages.

```{r get_ranks, eval=FALSE}
library(five38clubrankings)
rankings_2018 = get_club_rankings()
```

```{r get_country, echo=-(1:2)}
library(five38clubrankings)
data("rankings_2018")
get_country_averages(rankings_2018)
```


```{r get_league}
get_league_averages(rankings_2018)
```




